# Generated by Django 4.1.2 on 2023-05-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_commande_total_trans"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_categ", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name="produit", old_name="categorie", new_name="Category",
        ),
        migrations.AddField(
            model_name="client",
            name="nb_enfants",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="commande",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commande",
            name="status",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="commande",
            name="total_trans",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="commande",
            name="transaction_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="produit",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="CategorieSocio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="shop.categoriesocio",
            ),
        ),
    ]
