# Generated by Django 4.1.2 on 2023-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_categoriesocio_rename_categorie_produit_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="total_trans",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
